# Generated by Django 5.1.1 on 2024-09-04 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='version',
            old_name='name',
            new_name='version',
        ),
        migrations.AddField(
            model_name='version',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='version',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='version',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='version',
            name='version_code',
            field=models.CharField(default='v00', max_length=100),
            preserve_default=False,
        ),
    ]
